# Generated by Django 4.2.7 on 2024-05-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_subject_sujectmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SujectMarks',
            new_name='SubjectMarks',
        ),
    ]
